name: location_tracking_app
description: "Tracks users live location and provides a summery of time spent in some predefined locations"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Location
  geolocator: ^9.0.2

  # Background service support
  #flutter_background_service: ^4.0.1
  #flutter_background_service_android: ^4.0.1
  flutter_background_service: ^5.1.0

  permission_handler: ^11.3.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  # Mocks for Testing
  mockito: ^5.4.4

flutter:
  uses-material-design: true